baseURL = 'https://devsecfailureops.com/hot-takes/'
languageCode = 'en-us'
title = 'DevSecFailureOps'
theme = 'm10c'

[params]
  author = 'Peter Seale'
  description = "DevSecFailureOps: the intersection of Development, InfoSec, Operations, and also mortifying, pervasive Failure"
  avatar = './avatar-dignified-400x400.jpg'

[[params.social]]
  icon = "github"
  name = "GitHub"
  url = "https://github.com/pseale"

[[params.social]]
  icon = "twitter"
  name = "Twitter"
  url = "https://twitter.com/pseale"

[menu]
  [[menu.main]]
    identifier = "standard-disclaimer"
    name = "Standard disclaimer"
    url = "/posts/standard-disclaimer"
    weight = 1